title: Young Pirates of Europe

email: office@young-pirates.eu
facebook_username: youngpiratesEU
twitter_username: YoungPiratesEU
github_username: Fhavlonir/YPE-placeholder

include: 
  - _includes

site-css:
  - "/_includes/styling.css"

header_pages:
  - "elections.md"
  - "workwithus.md"
