title: Young Pirates of Europe

email: office@young-pirates.eu
facebook_username: youngpiratesEU
twitter_username: YoungPiratesEU
instagram_username: youngpirateseu

include: 
  - _includes
  - assets
  - fonts

site-css:
  - "/_includes/styling.css"

header_pages:
  - "members.md"
  - "board.md"
  - "epic.md"
  - "statutes.md"
  - "contact.md"
