title: Young Pirates of Europe

remote_theme: daattali/beautiful-jekyll@6.0.1

title-img: "icon.svg"

footer-extra: info.html

remove-ads: true

social-network-links:
  email: office@young-pirates.eu
  rss: false
  facebook: youngpiratesEU
  twitter: YoungPiratesEU
  github: Fhavlonir/YPE-placeholder
